language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"

install:
    - composer install --prefer-dist --dev
    - git config --global user.email "phpunit@example.com"
    - git config --global user.name "PHP Unit"

script: ant -keep-going
